language: node_js
node_js:
  - '8'

jobs:
  include:
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t pedidos_frontend . -f Dockerfile
        - docker images
        - docker tag pedidos_backend $DOCKER_USERNAME/pedidos_frontend
        - docker push $DOCKER_USERNAME/pedidos_frontend
